package uni.melb.au.utils;

public enum BehaviorRelation {
	// PRIME EVENT STRUCTURES
	CAUSALITY,
	INV_CAUSALITY,
	CONFLICT,
	CONCURRENCY,
	// ASYMMETRIC EVENT STRUCTURES
	ASYM_CONFLICT,
	INV_ASYM_CONFLICT
}
